### ISSUE TITLE
SQLite not supported? - Issue when running start:bundle

### ISSUE THREAD

**Issue by RFlintstone** [spacebarchat/spacebarchat#144]
I'm using CyberPanel to host websites although it doesn't seem to offer full MySQL support. My VPS is therefore running on MySQL Light which didn't gave me any issues until I tried to run the command `npm run start:bundle`. Is there a fix for this problem? I would really like to try this software out! :D 

Log:
```
root@37-187-197-249:~/fosscord-server/bundle# npm run start:bundle

> @fosscord/server@1.0.0 start:bundle
> node dist/bundle/src/start.js


███████╗ ██████╗ ███████╗███████╗ ██████╗ ██████╗ ██████╗ ██████╗
██╔════╝██╔═══██╗██╔════╝██╔════╝██╔════╝██╔═══██╗██╔══██╗██╔══██╗
█████╗  ██║   ██║███████╗███████╗██║     ██║   ██║██████╔╝██║  ██║
██╔══╝  ██║   ██║╚════██║╚════██║██║     ██║   ██║██╔══██╗██║  ██║
██║     ╚██████╔╝███████║███████║╚██████╗╚██████╔╝██║  ██║██████╔╝
╚═╝      ╚═════╝ ╚══════╝╚══════╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝╚═════╝

                fosscord-server | Pre-release (ec8d8e4)

Commit Hash: ec8d8e43c5de13c560c1c4038a24e2726601fe47 (ec8d8e4)
Cores: 2 (Using 2 thread(s).)

[Path] running in /root/fosscord-server/bundle/dist/bundle/src
[CPU] Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz Cores x2
[System] linux x64
[Process] running with PID: 12438
[Process] Warning fosscord is running as root, this highly discouraged and might expose your system vulnerable to                                                       attackers. Please run fosscord as a user without root privileges.
[Process] starting with 2 threads
[Process] worker 0 started.
Missing @yukikaze-bot/erlpack, electron-based desktop clients designed for discord.com will not be able to connec                                                      t!
[Process] worker 1 started.
[CDN] storage location: /root/fosscord-server/bundle/files
[Database] connecting to sqlite db
[Database] You are running sqlite! Please keep in mind that we recommend setting up a dedicated database!
DataTypeNotSupportedError: Data type "longtext" in "Message.content" is not supported by "sqlite" database.
    at DataTypeNotSupportedError.TypeORMError [as constructor] (/root/fosscord-server/bundle/node_modules/typeorm                                                      /error/TypeORMError.js:9:28)
    at new DataTypeNotSupportedError (/root/fosscord-server/bundle/node_modules/typeorm/error/DataTypeNotSupporte                                                      dError.js:9:28)
    at /root/fosscord-server/bundle/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:79:27
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validate (/root/fosscord-server/bundle/node_modules/typeorm/metadata-builder/Entit                                                      yMetadataValidator.js:76:36)
    at /root/fosscord-server/bundle/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:44:74
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validateMany (/root/fosscord-server/bundle/node_modules/typeorm/metadata-builder/E                                                      ntityMetadataValidator.js:44:25)
    at Connection.buildMetadatas (/root/fosscord-server/bundle/node_modules/typeorm/connection/Connection.js:519:                                                      33)
    at Connection.<anonymous> (/root/fosscord-server/bundle/node_modules/typeorm/connection/Connection.js:126:30)
    at step (/root/fosscord-server/bundle/node_modules/tslib/tslib.js:143:27)
    at Object.next (/root/fosscord-server/bundle/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/root/fosscord-server/bundle/node_modules/tslib/tslib.js:114:62)
DataTypeNotSupportedError: Data type "longtext" in "Message.content" is not supported by "sqlite" database.
    at DataTypeNotSupportedError.TypeORMError [as constructor] (/root/fosscord-server/bundle/node_modules/typeorm                                                      /error/TypeORMError.js:9:28)
    at new DataTypeNotSupportedError (/root/fosscord-server/bundle/node_modules/typeorm/error/DataTypeNotSupporte                                                      dError.js:9:28)
    at /root/fosscord-server/bundle/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:79:27
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validate (/root/fosscord-server/bundle/node_modules/typeorm/metadata-builder/Entit                                                      yMetadataValidator.js:76:36)
    at /root/fosscord-server/bundle/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:44:74
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validateMany (/root/fosscord-server/bundle/node_modules/typeorm/metadata-builder/E                                                      ntityMetadataValidator.js:44:25)
    at Connection.buildMetadatas (/root/fosscord-server/bundle/node_modules/typeorm/connection/Connection.js:519:                                                      33)
    at Connection.<anonymous> (/root/fosscord-server/bundle/node_modules/typeorm/connection/Connection.js:126:30)
    at step (/root/fosscord-server/bundle/node_modules/tslib/tslib.js:143:27)
    at Object.next (/root/fosscord-server/bundle/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/root/fosscord-server/bundle/node_modules/tslib/tslib.js:114:62) Promise {
  <rejected> DataTypeNotSupportedError: Data type "longtext" in "Message.content" is not supported by "sqlite" da                                                      tabase.
      at DataTypeNotSupportedError.TypeORMError [as constructor] (/root/fosscord-server/bundle/node_modules/typeo                                                      rm/error/TypeORMError.js:9:28)
      at new DataTypeNotSupportedError (/root/fosscord-server/bundle/node_modules/typeorm/error/DataTypeNotSuppor                                                      tedError.js:9:28)
      at /root/fosscord-server/bundle/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:79:27
      at Array.forEach (<anonymous>)
      at EntityMetadataValidator.validate (/root/fosscord-server/bundle/node_modules/typeorm/metadata-builder/Ent                                                      ityMetadataValidator.js:76:36)
      at /root/fosscord-server/bundle/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:44:74
      at Array.forEach (<anonymous>)
      at EntityMetadataValidator.validateMany (/root/fosscord-server/bundle/node_modules/typeorm/metadata-builder                                                      /EntityMetadataValidator.js:44:25)
      at Connection.buildMetadatas (/root/fosscord-server/bundle/node_modules/typeorm/connection/Connection.js:51                                                      9:33)
      at Connection.<anonymous> (/root/fosscord-server/bundle/node_modules/typeorm/connection/Connection.js:126:3                                                      0)
      at step (/root/fosscord-server/bundle/node_modules/tslib/tslib.js:143:27)
      at Object.next (/root/fosscord-server/bundle/node_modules/tslib/tslib.js:124:57)
      at fulfilled (/root/fosscord-server/bundle/node_modules/tslib/tslib.js:114:62)
}
Missing @yukikaze-bot/erlpack, electron-based desktop clients designed for discord.com will not be able to connec                                                      t!
[CDN] storage location: /root/fosscord-server/bundle/files
[Database] connecting to sqlite db
[Database] You are running sqlite! Please keep in mind that we recommend setting up a dedicated database!
DataTypeNotSupportedError: Data type "longtext" in "Message.content" is not supported by "sqlite" database.
    at DataTypeNotSupportedError.TypeORMError [as constructor] (/root/fosscord-server/bundle/node_modules/typeorm                                                      /error/TypeORMError.js:9:28)
    at new DataTypeNotSupportedError (/root/fosscord-server/bundle/node_modules/typeorm/error/DataTypeNotSupporte                                                      dError.js:9:28)
    at /root/fosscord-server/bundle/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:79:27
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validate (/root/fosscord-server/bundle/node_modules/typeorm/metadata-builder/Entit                                                      yMetadataValidator.js:76:36)
    at /root/fosscord-server/bundle/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:44:74
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validateMany (/root/fosscord-server/bundle/node_modules/typeorm/metadata-builder/E                                                      ntityMetadataValidator.js:44:25)
    at Connection.buildMetadatas (/root/fosscord-server/bundle/node_modules/typeorm/connection/Connection.js:519:                                                      33)
    at Connection.<anonymous> (/root/fosscord-server/bundle/node_modules/typeorm/connection/Connection.js:126:30)
    at step (/root/fosscord-server/bundle/node_modules/tslib/tslib.js:143:27)
    at Object.next (/root/fosscord-server/bundle/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/root/fosscord-server/bundle/node_modules/tslib/tslib.js:114:62)
DataTypeNotSupportedError: Data type "longtext" in "Message.content" is not supported by "sqlite" database.
    at DataTypeNotSupportedError.TypeORMError [as constructor] (/root/fosscord-server/bundle/node_modules/typeorm                                                      /error/TypeORMError.js:9:28)
    at new DataTypeNotSupportedError (/root/fosscord-server/bundle/node_modules/typeorm/error/DataTypeNotSupporte                                                      dError.js:9:28)
    at /root/fosscord-server/bundle/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:79:27
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validate (/root/fosscord-server/bundle/node_modules/typeorm/metadata-builder/Entit                                                      yMetadataValidator.js:76:36)
    at /root/fosscord-server/bundle/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:44:74
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validateMany (/root/fosscord-server/bundle/node_modules/typeorm/metadata-builder/E                                                      ntityMetadataValidator.js:44:25)
    at Connection.buildMetadatas (/root/fosscord-server/bundle/node_modules/typeorm/connection/Connection.js:519:                                                      33)
    at Connection.<anonymous> (/root/fosscord-server/bundle/node_modules/typeorm/connection/Connection.js:126:30)
    at step (/root/fosscord-server/bundle/node_modules/tslib/tslib.js:143:27)
    at Object.next (/root/fosscord-server/bundle/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/root/fosscord-server/bundle/node_modules/tslib/tslib.js:114:62) Promise {
  <rejected> DataTypeNotSupportedError: Data type "longtext" in "Message.content" is not supported by "sqlite" da                                                      tabase.
      at DataTypeNotSupportedError.TypeORMError [as constructor] (/root/fosscord-server/bundle/node_modules/typeo                                                      rm/error/TypeORMError.js:9:28)
      at new DataTypeNotSupportedError (/root/fosscord-server/bundle/node_modules/typeorm/error/DataTypeNotSuppor                                                      tedError.js:9:28)
      at /root/fosscord-server/bundle/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:79:27
      at Array.forEach (<anonymous>)
      at EntityMetadataValidator.validate (/root/fosscord-server/bundle/node_modules/typeorm/metadata-builder/Ent                                                      ityMetadataValidator.js:76:36)
      at /root/fosscord-server/bundle/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:44:74
      at Array.forEach (<anonymous>)
      at EntityMetadataValidator.validateMany (/root/fosscord-server/bundle/node_modules/typeorm/metadata-builder                                                      /EntityMetadataValidator.js:44:25)
      at Connection.buildMetadatas (/root/fosscord-server/bundle/node_modules/typeorm/connection/Connection.js:51                                                      9:33)
      at Connection.<anonymous> (/root/fosscord-server/bundle/node_modules/typeorm/connection/Connection.js:126:3                                                      0)
      at step (/root/fosscord-server/bundle/node_modules/tslib/tslib.js:143:27)
      at Object.next (/root/fosscord-server/bundle/node_modules/tslib/tslib.js:124:57)
      at fulfilled (/root/fosscord-server/bundle/node_modules/tslib/tslib.js:114:62)
}
^C
root@37-187-197-249:~/fosscord-server/bundle# python3 --version
Python 3.6.9
root@37-187-197-249:~/fosscord-server/bundle# node -v
v17.6.0
root@37-187-197-249:~/fosscord-server/bundle# npm -v
8.5.3
```

**Comment by ImAaronFR** [comment]
This is a issue with a commit that needs to be reverted but for now you can edit it yourself in 

`util/src/entities/Message.ts` on line 109 edit `@Column({ type: "longtext", nullable: true })` to `@Column({ nullable: true })`

**Comment by keneshindev** [comment]
First of all, it's not MySQL Lite, it's SQLite which are different (does MySQL Lite even exist?)
Second, you'll need to revert https://github.com/fosscord/fosscord-server/commit/ec8d8e43c5de13c560c1c4038a24e2726601fe47

**Comment by RFlintstone** [comment]
> This is a issue with a commit that needs to be reverted but for now you can edit it yourself in

> you'll need to revert https://github.com/fosscord/fosscord-server/commit/ec8d8e43c5de13c560c1c4038a24e2726601fe47

Thanks, this did the trick! - Also out of curiousity, when will the admin panel become a feature?

> does MySQL Lite even exist?

Nope, it doesn't. Quick writing mistake.

**Comment by KaKi87** [comment]
Hello, I'm currently experiencing a similar error on `master` :

```
DataTypeNotSupportedError: Data type "Object" in "UserGroup.parent" is not supported by "sqlite" database.
    at /node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:90:27
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validate (/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:86:18)
    at /node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:38:58
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validateMany (/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:38:25)
    at DataSource.buildMetadatas (/node_modules/typeorm/data-source/DataSource.js:446:33)
    at async DataSource.initialize (/node_modules/typeorm/data-source/DataSource.js:130:13)
    at async initDatabase (/dist/util/util/Database.js:83:43)
    at async main (/dist/bundle/Server.js:47:5)
```

Thanks

**Comment by MaddyUnderStars** [comment]
@KaKi87 are you on the master branch of *this* repo? This is not the server. Please see [the fosscord docs](https://docs.fosscord.com/setup/server/) for instructions on how to setup the server.

**Comment by KaKi87** [comment]
> are you on the master branch of _this_ repo?

No, of the `fosscord/fosscord-server` repo.

This issue is indeed at the wrong place but that's the one I found from a conversation on Discord.

**Comment by MaddyUnderStars** [comment]
SQLite *is* supported, but it is not recommend for production servers. You are not on the latest version of Fosscord server, because `UserGroup` mentioned in the error you provided does not exist in the latest version. If you've already updated, delete the `dist` folder, build and run again.

**Comment by KaKi87** [comment]
> SQLite _is_ supported, but it is not recommend for production servers.

No worries, I'm using it for testing purposes only.

> If you've already updated, delete the `dist` folder

That was the step I was missing !

I've ran `git pull`, `npm i` and `npm run setup` multiple times already, but it wouldn't do any good until I deleted `dist` beforehand.

Thanks.
